### ISSUE TITLE
 RaspberryPi + rd1 Set Up Guide

### ISSUE THREAD

**Issue by rodriwp** [asrob-uc3m/robotDevastation-robots#5] opened 2015-02-08 17:47 UTC
Will we nice to have a complete guide about seting up raspberrypi without using the image of rd1. The documentation also will help with rd2 with ardubot   and ardubot versions.

**Comment by jgvictores** [comment] 2015-02-09 17:55
This issue is almost a duplicate of https://github.com/asrob-uc3m/robotDevastation-robots/issues/3, but we can use it to focus on RD1. For now the two relevant links are:
- http://asrob.uc3m.es/index.php/C%C3%B3mo_montar_el_robot_RD1
- http://asrob.uc3m.es/rd1doc/rd1_install_on_raspbian_7.html

**Comment by jgvictores** [comment] 2015-06-03 17:50
RD1 depreciated. Docuemented RD2 at http://asrob.uc3m.es/index.php/C%C3%B3mo_montar_el_robot_RD2.

**Closed as completed** 2015-06-03 17:51 UTC
